### PR TITLE
Escape password when it starts with dash

### PR DESCRIPTION
**Pull request by esanchezm**
Hello! First of all, thanks for putting this in a docker image!

I tried to use it but turns out my password starts with a dash (`-`) so xdotool fails 😅 So, in this PR I'm escaping it using a simple regular expression. I tried it locally and it works fine and I'm able to login now

Maybe this needs to be backported to other python scripts but right now I'm only using the desktop version and I haven't check the other files...

### CODE REVIEW

**Comment by MRColorR** [comment]
Thanks for contacting us and for your input, it is a valuable addition. 
I will check it out right away and proceed with the integration if it is positive. It would be a good idea to handle escaping more special characters if you feel comfortable doing it now before the merge without having to open more pr later.

**Comment by esanchezm** [comment]
I don't think you need to escape anything else than that. A password beginning with dash will just interfere with `subprocess.run()` as it will be interpreted as a command flag. Any other case is not needed because there's no shell involved that could interfere.

**Comment by MRColorR** [comment]
> I don't think you need to escape anything else than that. A password beginning with dash will just interfere with `subprocess.run()` as it will be interpreted as a command flag. Any other case is not needed because there's no shell involved that could interfere.

Great, i was already getting ahead 😅.
I'll merge it ASAP. Thanks  for your help

**Comment by MRColorR** [comment]
> cannot extract magic number

the open PR is for grass desktop app, your issue is for grass extension , let's open a standalone issue :)

**Review by MRColorR — APPROVED** [review]
your approach is correct and will suffice, ready to merge

**Pull request merged**
